### ISSUE TITLE
npm install && npm start will not work 

### ISSUE THREAD

**Issue by liamlindy** [john-smilga/react-hooks-tutorial-2020#32]
I cloned this git repository into a folder then ran `npm install && npm start ` and got all kinds of errors and I am not sure why. Up until now in the react course everything was working just fine

**Comment by Sjones91** [comment]
Did you ever fix this issue? I'm having the same problem, it's saying for me module not found on a certain package in node modules although I can see it in the directory where it's looking for it.

**Comment by rahulks5** [comment]
I have fixed it. Guys you just have to "npm install'' then run "npm audit fix" and after this run again "npm audit fix --force".
This worked for me you can also try this. Hope this will help you out.

**Comment by m-fadi** [comment]
THis worked for me:

https://stackoverflow.com/a/69713899/18747358

**Comment by Devoustate** [comment]
Same problem here, this guy don't care about people using these files
